### ISSUE TITLE
Kane's error: System Rule 'Order.process_calculateddeliverycharge' caused the following exception: AttributeError("'Order' object has no attribute 'passed_obj'",)

### ISSUE THREAD

**Issue by kbower** [kbower/tickettest1#1415]
_Imported from trac ticket 1415.
Created by **kbower**
Opened in trac: Jan 31, 2012, 7:06:14 AM
Last modified in trac: Jan 31, 2012, 4:08:06 PM_
***
Stack
```
[Mon Jan 30 17:31:37 2012] [error] [client 173.221.136.228] File '/home/rarch/trunk/src/appserver/pylotengine/model/autoupdate.py', line 100 in process
[Mon Jan 30 17:31:37 2012] [error] [client 173.221.136.228]   return cfg.system_rule_allow_none(rule_name % classname, **params)
[Mon Jan 30 17:31:37 2012] [error] [client 173.221.136.228] File '/home/rarch/trunk/src/appserver/pylotengine/model/objects.py', line 6563 in system_rule_allow_none
[Mon Jan 30 17:31:37 2012] [error] [client 173.221.136.228]   raise RError("System Rule '%s' caused the following exception: %r\\n%s" % (rulename, e, traceback.format_exc()))
[Mon Jan 30 17:31:37 2012] [error] [client 173.221.136.228] RError: System Rule 'Order.process_calculateddeliverycharge' caused the following exception: AttributeError("'Order' object has no attribute 'passed_obj'",)
[Mon Jan 30 17:31:37 2012] [error] [client 173.221.136.228] Traceback (most recent call last):
[Mon Jan 30 17:31:37 2012] [error] [client 173.221.136.228]   File "/home/rarch/trunk/src/appserver/pylotengine/model/objects.py", line 6559, in system_rule_allow_none
[Mon Jan 30 17:31:37 2012] [error] [client 173.221.136.228]     return params['__rule_fn__']()
[Mon Jan 30 17:31:37 2012] [error] [client 173.221.136.228]   File "Order.process_calculateddeliverycharge", line 10, in __rule_fn__
[Mon Jan 30 17:31:37 2012] [error] [client 173.221.136.228]   File "/home/rarch/trunk/src/appserver/pylotengine/model/objects.py", line 128, in __getattr__
[Mon Jan 30 17:31:37 2012] [error] [client 173.221.136.228]     raise AttributeError("'%s' object has no attribute '%s'" % (self.__class__.__name__, name))
[Mon Jan 30 17:31:37 2012] [error] [client 173.221.136.228] AttributeError: 'Order' object has no attribute 'passed_obj'
```

**Comment by kbower** [comment]
_**kbower** trac comment on Jan 31, 2012, 8:13:55 AM:_


The error message below was reported when a store was attempting to save an order. They could not save it in POS so keyed it in GERS. The two factors that stand out are the order was set up as a T08 shipping type, with the LET discount code. The GERS order number is 0130208UUDW

I just heard from our East Colonial store. They ran across the same error. This was a T17 shipping type and they were also using the LET code. The manager removed the LET  code, reduced the item with a manual override, and the order saved. 

Not sure if this was just the LET code, or when it is used in combination with a Txx shipping zone. I tried to replicate this in Train but could not get the same  error.

Tim


```
A fatal error was encountered when communicating with the server.

Error message:
RError: System Rule 'Order.process_calculateddeliverycharge' caused the following exception: AttributeError("'Order' object has no attribute 'passed_obj'",)
Traceback (most recent call last):
  File "/home/rarch/trunk/src/appserver/pylotengine/model/objects.py", line 6559, in system_rule_allow_none
    return params['__rule_fn__']()
  File "Order.process_calculateddeliverycharge", line 10, in __rule_fn__
  File "/home/rarch/trunk/src/appserver/pylotengine/model/objects.py", line 128, in __getattr__
    raise AttributeError("'%s' object has no attribute '%s'" % (self.__class__.__name__, name))
AttributeError: 'Order' object has no attribute 'passed_obj' 
```

**Comment by kbower** [comment]
_**kbower** trac comment on Jan 31, 2012, 9:08:03 AM:_

(Changeset [[2244]](../commit/80ddcf839f4d6cd611e9e1822263a80d46f2ae13))
 * fixes #1415 (Kane's: System Rule 'Order.process_calculateddeliverycharge' caused the following exception: AttributeError("'Order' object has no attribute 'passed_obj'",))

**Comment by kbower** [comment]
_**kbower** trac status change on Jan 31, 2012, 9:08:03 AM:_ **closed**

**Comment by kbower** [comment]
_**kbower** trac comment on Jan 31, 2012, 9:13:04 AM:_

see [[2245]](../commit/d0fac6791f23b79429dfbdcf496f60db2327c5a7)

**Comment by kbower** [comment]
_**kbower** trac status change on Jan 31, 2012, 9:13:04 AM:_ **reopened**

**Comment by kbower** [comment]
_**kbower** trac comment on Jan 31, 2012, 2:32:14 PM:_

see http://groups.google.com/group/sqlalchemy/browse_thread/thread/ee3860d13811adb4

**Comment by kbower** [comment]
_**kbower** trac comment on Jan 31, 2012, 2:40:15 PM:_

(Changeset [[2249]](../commit/c5891a830eb31fb807ce5244c1849da54eaa6fcb))
 * sqlalchemy upgrade from [[2113]](../commit/3aa25522a17fffb5497ec65c0b1e6a7c0eb8f8f7) honors expunge cascade, which causes problems.  Remove this by default from relationships and backrefs
   * fixes #1415 (System Rule 'Order.process_calculateddeliverycharge' caused the following exception:AttributeError("'Order' object has no attribute 'passed_obj')
   * presumably also fixes [#1420](1420) (InvalidRequestError: Instance '<Order at 0x2b4fdc1b9890>' is not persistent within this Session)

**Comment by kbower** [comment]
_**kbower** trac status change on Jan 31, 2012, 2:40:15 PM:_ **closed**

**Comment by kbower** [comment]
_**kbower** trac comment on Jan 31, 2012, 4:08:06 PM:_

The cause of this issue was an `OrderDetailDiscount` being removed from an `OrderDetail` (this is normal when trying to find best discount for customer).  SQLAlchemy was expunging the `OrderDetailDiscount` which cascaded to the `Order`.
