### ISSUE TITLE
Product Maintenance Phase II

### ISSUE THREAD

**Issue by kentbower** [kbower/tickettest1#2374]
_Imported from trac ticket 2374.
Created by **sjohnson**
Opened in trac: Jun 13, 2013, 11:26:02 AM
Last modified in trac: Mar 3, 2014, 3:17:31 PM_
***
_by sjohnson:_
Add Improvements here that aren't bugs from the 1st Release

***
* kbower attached [ceaeeiaa.png](https://trac.retailarchitects.com/trac/attachment/ticket/2374/ceaeeiaa.png) on Jun 20, 2013, 7:36:06 AM
* kbower attached [untitled-part.png](https://trac.retailarchitects.com/trac/attachment/ticket/2374/untitled-part.png) on Jun 26, 2013, 12:23:28 PM
* kbower attached [fbjcfefd.png](https://trac.retailarchitects.com/trac/attachment/ticket/2374/fbjcfefd.png) on Jun 26, 2013, 12:32:34 PM
* kbower attached [jihhdfhg.png](https://trac.retailarchitects.com/trac/attachment/ticket/2374/jihhdfhg.png) on Jun 27, 2013, 10:14:32 AM
* sjohnson attached [aeheabdi.png](https://trac.retailarchitects.com/trac/attachment/ticket/2374/aeheabdi.png) on Aug 22, 2013, 11:51:00 AM

**Comment by kentbower** [comment]
_**sjohnson** trac comment on Jun 13, 2013, 11:30:36 AM:_

In Custom properties, when adding a value, the column should respect the value Type and present Y or N as a dropdown for a boolean or a calender for a date, etc.

**Comment by kentbower** [comment]
_**sjohnson** trac comment on Jun 19, 2013, 3:48:54 PM:_

Need SERIALNUMBERCAPTURE and STORECARD Indicators added to screen.

**Comment by kentbower** [comment]
_**kbower** trac comment on Jun 19, 2013, 4:03:19 PM:_

Replying to [sjohnson](comment:2):
> Need SERIALNUMBERCAPTURE and STORECARD Indicators added to screen.


Also, when setting Store Card tick box, serialnumbercapture needs to be validated that it is set (or automatically set)

(Ticket [#2616](2616))

**Comment by kentbower** [comment]
_**kbower** trac comment on Jun 20, 2013, 7:36:06 AM:_

Visual, UI and graphic design observations for product screen.

[[Image(ceaeeiaa.png)]]

**Comment by kentbower** [comment]
_**mpisarski** trac comment on Jun 20, 2013, 9:50:08 AM:_

Thanks for the detailed screen cap!
I am working on cleaning much of this up right now.
The Product Lookup is supposed to be the old query only screen to give out to sales folks. Looks like my commit needs a data update to update the menu data...
Working on it :)

Replying to [kbower](comment:4):
> Visual, UI and graphic design observations for product screen.
> 
> [[Image(ceaeeiaa.png)]]

**Comment by kentbower** [comment]
_**mpisarski** trac comment on Jun 20, 2013, 3:36:42 PM:_

(Changeset [[4267]](../commit/d0a475c2cc55c3f636ce0984a3136950374d0812))
* fix menu items for Product Search and Products #all (re #1043 #2374)

**Comment by kentbower** [comment]
_**mpisarski** trac comment on Jun 21, 2013, 12:25:11 PM:_

(Changeset [[4269]](../commit/b530c8bafb46bdd51991d8ffe9198b4da57438be))
* Product Maintenance Updates (sprint feedback) #all
  * closes #1043 - add server side validations for warranty, value, and store card flags
  * add storecard and serialnumbercapture to product screen
  * add Product Notice drop down (drop codes) to the product screen (re #2374)
  * when creating a new product, should be able to add brand new images at the same time. (re #2374)
  * main product screen re-arrange to allow for more input fields.

**Comment by kentbower** [comment]
_**mpisarski** trac comment on Jun 21, 2013, 12:26:31 PM:_

Refer to the original ticket #1043 for the product check digit code...

**Comment by kentbower** [comment]
_**mpisarski** trac comment on Jun 21, 2013, 4:27:23 PM:_

(Changeset [[4272]](../commit/2d11b2e0e7e65298b96be8818a0525cfa0079b0c))
* Product Maintenance - add Store Distribution tab to allow defining desired product level (ITM2STORE_DIST) records. re #2374 #all

**Comment by kentbower** [comment]
_**kbower** trac comment on Jun 26, 2013, 12:23:28 PM:_

Relationships need labels in labels.properties.
There are two "RelatedItems" and two SPIFFs, two Warranty Coverages.

[[Image(untitled-part.png)]]

**Comment by kentbower** [comment]
_**kbower** trac comment on Jun 26, 2013, 12:32:34 PM:_

Product.action_set_product_flags needs label:

[[Image(fbjcfefd.png)]]

**Comment by kentbower** [comment]
_**kbower** trac comment on Jun 26, 2013, 12:46:34 PM:_

## wait cursor needed

When you click on a queried product, we need an hourglass or progress bar or something to show loft is fetching the product.  It takes seconds to load a product for Kane's and you can't tell whether anything is going to happen or if you need to click again or double click or what went "wrong."

**Comment by kentbower** [comment]
_**sjohnson** trac comment on Jun 26, 2013, 2:02:40 PM:_

When returning the History tab with a new product after a previous product search, the previous product is still displayed.

**Comment by kentbower** [comment]
_**kbower** trac comment on Jun 27, 2013, 10:14:32 AM:_

Meaningful Advanced Searches leave no room for the grid.  Please add a minimum height like the order query screen does.

[[Image(jihhdfhg.png)]]

**Comment by kentbower** [comment]
_**sjohnson** trac comment on Aug 15, 2013, 10:38:48 AM:_

Please add SALESPROMPTS and LEADDAYS to the Products screen.

**Comment by kentbower** [comment]
_**sjohnson** trac comment on Aug 16, 2013, 4:11:34 PM:_

Additions to Products - This is mostly from Sal's email.  I removed the things that are already complete and documented the rest here.
 - Salesprompts
 - Leaddays
 - DROP_DT
 - Freight% = frt_fac
 - Freight $ = ((repl_cst * frt_fac) / 100)
 - Landed replacement cost = repl_cst + ((repl_cst * frt_fac) / 100)
 -  The warranty flag should actually take you to a pop up where you can associate a warranty sku with the inventory sku
 - A link to go to the inventory summary for the product you are working on the product page
 - Package components needs vendor, VSN, and description displayed
 - When you look up a regular inventory sku you should be able to see which packages it resides in similar to how when looking up a package you see the components

**Comment by kentbower** [comment]
_**sjohnson** trac comment on Aug 22, 2013, 11:51:00 AM:_

Kent doesn't like the tg in the image file path.

[[Image(aeheabdi.png)]]

**Comment by kentbower** [comment]
_**mpisarski** trac comment on Aug 26, 2013, 1:14:39 PM:_

Replying to [sjohnson](comment:22):
> Kent doesn't like the tg in the image file path.
> 
> [[Image(aeheabdi.png)]]


Not much we can do about that unless we remove all reference to tg.

**Comment by kentbower** [comment]
_**sjohnson** trac comment on Aug 26, 2013, 2:39:06 PM:_

Tabbing field to field does not work.

**Comment by kentbower** [comment]
_**sjohnson** trac comment on Sep 3, 2013, 3:47:42 PM:_

A useful action would be to set the drop code (notice) on a group of items. Please include a checkbox to clear the notice as well.

**Comment by kentbower** [comment]
_**sjohnson** trac comment on Sep 4, 2013, 4:37:07 PM:_

When trying to add a new custom property with a different Target, but the same property that has already been entered, Loft thinks you are trying to overwrite a record.  Need to recognize a target/property pairing as unique.

**Comment by kentbower** [comment]
_**mpisarski** trac comment on Sep 5, 2013, 4:08:34 PM:_

(Changeset [[4520]](../commit/7baf93f8c91d5c49c3c7f9dd9a5ce7126cfc80c9))
* Product Maintenance updates (re #2374) #all
  * fix History tab - clears on product change, and simplifies the subform.
  * label fixes 
  * busy cursor on product GET.

**Comment by kentbower** [comment]
_**sjohnson** trac comment on Sep 10, 2013, 3:07:05 PM:_

Screen needs to retain some basic product information at the top of the screen (Product ID, Description, perhaps vendor) as you visit the other product tabs.

**Comment by kentbower** [comment]
_**mpisarski** trac comment on Sep 12, 2013, 2:34:47 PM:_

(Changeset [[4540]](../commit/e50691b13f5a27d108d04b57d78e11f9e96f79c0))
* Product maintenance fixes. re #2374
  * fix custom properties to allow same property to be defined for multiple targets.
  * move "back to search..." link to be on the main screen instead of child tab.
  * fix product edit layout.

**Comment by kentbower** [comment]
_**mpisarski** trac comment on Sep 16, 2013, 12:57:57 PM:_

(Changeset [[4549]](../commit/4425c058deeb7bb27452464b9e0b68b920fe6eb5))
* fix image upload via Loft for products. (re #2374) #all
  * flex loade() strips type information from the file being loaded, so when it is saved the OS does not know what type of data is in the file.
  * this requires that images uploaded through Loft (not URLs) be removed from the server and products.

**Comment by kentbower** [comment]
_**sjohnson** trac comment on Sep 20, 2013, 12:18:00 PM:_

Need to add Stockeditem to screen.  It appears to be defaulting to Y when creating a new item.  I created a Labor type sku and it defaulted to stockeditem = Y so we need to be able to specify and update the field.

Also Got this error when entering in a bad subclass:
Error message:
FlushTimeException: IntegrityError('(IntegrityError) insert or update on table "products" violates foreign key constraint "products_subclassid_fkey"\nDETAIL:  Key (productclassid, subclassid)=(UPOC, 058) is not present in table "subclasses".\n',)
Traceback (most recent call last):
  File "/home/rarch/trunk/src/appserver/pylotengine/sqla.py", line 344, in flush
    super(CustomSession, self).flush(objects)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/session.py", line 1608, in flush
    self._flush(objects)
  File "/home/rarch/trunk/src/appserver/pylotengine/sqla.py", line 379, in _flush
    super(CustomSession, self)._flush(objects)
  File &q ...

**Comment by kentbower** [comment]
_**kbower** trac comment on Oct 14, 2013, 12:06:05 PM:_

(Changeset [[4658]](../commit/ad2fdc5bcb791b8cb9a7f0bf98bda8edd7a26661))
* fix product grid deletion (when grid sorted), re #2374 #all

**Comment by kentbower** [comment]
_**sjohnson** trac comment on Oct 25, 2013, 2:38:13 PM:_

Error when adding new product:
FlushTimeException: IntegrityError('(IntegrityError) ORA-01400: cannot insert NULL into ("INV"."ITM"."LST_ACT_DT")\n',)

**Comment by kentbower** [comment]
_**sjohnson** trac comment on Nov 8, 2013, 1:07:38 PM:_

Error on Morris: ORA-64013:INSERT operation disallowed on virtual columns\n

**Comment by kentbower** [comment]
_**sjohnson** trac comment on Nov 8, 2013, 4:45:02 PM:_

Got this when I tried it on Morris.
A fatal error was encountered when communicating with the server.

Error message:
FlushTimeException: DatabaseError('(DatabaseError) ORA-54013: INSERT operation disallowed on virtual columns\n',)
Traceback (most recent call last):
  File "/home/train/trunk/src/appserver/pylotengine/sqla.py", line 344, in flush
    super(CustomSession, self).flush(objects)

**Comment by kentbower** [comment]
_**sshah** trac comment on Nov 8, 2013, 5:03:11 PM:_

Problem is that in 11g you can create virtual columns and ITM.FRT_FAC is of that kind of column. This requires a different way to insert into the table. Need to do some more research.

select * from sys.all_tab_cols where VIRTUAL_COLUMN = 'YES';

**Comment by kentbower** [comment]
_**mpisarski** trac comment on Dec 6, 2013, 12:59:08 PM:_

(Changeset [[4818]](../commit/4d873bf013983ff3477bfd1308f641e44e14ca27))
* Product Maintenance update #all re #2374
  * add stocked item (inventory) flag
  * add last modified
  * invoice cost
 * still have to deal with virtual columns

**Comment by kentbower** [comment]
_**mpisarski** trac comment on Dec 13, 2013, 11:39:01 AM:_

From Sal:

 Spiff setup in item. In GERS you would detail on the spiff field in ITEM and it takes you to a screen where you set beginning and ending dates, spiff amount, minimum retail and spiff code. I see that missing in LOFT item screen. I looked in the LOFT spiff calendar screen but it appears that just queries spiffs but no way to create one.

**Comment by kentbower** [comment]
_**mpisarski** trac comment on Mar 3, 2014, 3:17:31 PM:_

(Changeset [[5123]](../commit/0997f5dce43ef4488b8f55efbcbb4a184eefac9c))
* Product Maintenance Phase II (closes #2374) #all
 * Product Maintenance remove notice saves properly and clears noticedate (fixes [#2628](2628))
 * Fix stockeditem flag to be updated (with user indicator) when Product.typeid is changed (based on ProductType.stockeditem flag)
 * REFACTOR: change all vendo and vendorobj references to be vendorid and vendor, respectively to bring merchandising in line with our conventions.

**Comment by kentbower** [comment]
_**mpisarski** trac status change on Mar 3, 2014, 3:17:31 PM:_ **closed**
