### ISSUE TITLE
import paramiko crash

### ISSUE THREAD

**Issue by kentbower** [kbower/tickettest1#2438]
_Imported from trac ticket 2438.
Created by **kbower**
Opened in trac: Aug 7, 2013, 9:05:27 AM
Last modified in trac: Dec 23, 2015, 10:28:01 AM_
***
_by kbower:_
No problem if there was a reason to not use the latest, but something crashes on kan train:

```

>>> import paramiko
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/paramiko/__init__.py", line 62, in <module>
  File "build/bdist.linux-x86_64/egg/paramiko/transport.py", line 33, in <module>
  File "build/bdist.linux-x86_64/egg/paramiko/util.py", line 33, in <module>
  File "build/bdist.linux-x86_64/egg/paramiko/common.py", line 98, in <module>
  File "build/bdist.linux-x86_64/egg/Crypto/Random/__init__.py", line 29, in <module>
  File "build/bdist.linux-x86_64/egg/Crypto/Random/_UserFriendlyRNG.py", line 38, in <module>
  File "build/bdist.linux-x86_64/egg/Crypto/Random/Fortuna/FortunaAccumulator.py", line 39, in <module>
  File "build/bdist.linux-x86_64/egg/Crypto/Random/Fortuna/FortunaGenerator.py", line 34, in <module>
  File "build/bdist.linux-x86_64/egg/Crypto/Util/number.py", line 57, in <module>
PowmInsecureWarning: Not using mpz_powm_sec.  You should rebuild using libgmp >= 5 to avoid timing attack vulnerability.
>>>
```

You seen that before?

On 8/7/2013 9:01 AM, Sameer Shah wrote:

**Comment by kentbower** [comment]
_**kbower** trac comment on Aug 7, 2013, 9:07:18 AM:_

Note, it might be the crypto library.

**Comment by kentbower** [comment]
_**kbower** trac comment on Aug 7, 2013, 9:26:17 AM:_

libgmp:
```
[root@kan ~]# rpm -q gmp
gmp-4.1.4-10.el5
gmp-4.1.4-10.el5
```

But this is the same on my dev VM, so doesn't seem to be the only reason.

**Comment by kentbower** [comment]
_**kbower** trac comment on Aug 7, 2013, 10:02:24 AM:_

http://stackoverflow.com/questions/2709661/pycrypto-and-gmp-library-not-found-error-mac-os-10-6-3

Error is caused by libgmp being there for install of pycrypto, but too low version.  (On our dev boxes, it isn't available, so slowmath is used with no error.)

Running `yum install gmp-devel` on dev box and reinstalling pycrypto simulates the kan server.  (Hint: if `ls /usr/lib/libgmp*` then it is available for pycrypto install)

**Ideal solution:** compile or install libgmp >= 5 and then rebuild pycrypto, so fast math is available for crypt algorithms.

**Comment by kentbower** [comment]
_**kbower** trac comment on Aug 7, 2013, 10:06:03 AM:_

If only eld needs this interface, we are safe for the time being, but my guess is this will crop up again.

**Comment by kentbower** [comment]
_**kbower** trac status change on Aug 7, 2013, 10:06:03 AM:_ **new**
