### ISSUE TITLE
Rule crash: Cannot save new order

### ISSUE THREAD

**Issue by kbower** [kbower/tickettest1#534]
_Imported from trac ticket 534.
Created by **kbower**
Opened in trac: Jan 10, 2011, 3:38:09 PM
Last modified in trac: Jan 10, 2011, 4:05:55 PM_
***
_by kbower:_
Error message:
RError: Order Rule 'codrules' caused the following exception: TypeError("unsupported operand type(s) for -: 'datetime.date' and 'datetime.datetime'",)
Traceback (most recent call last):
  File "/home/rarch/trunk/src/appserver/pylotengine/model/objects.py", line 4891, in run_save_rules
    stop_rules = scope['__rule_fn__']()
  File "codrules", line 4, in __rule_fn__
TypeError: unsupported operand type(s) for -: 'datetime.date' and 'datetime.datetime'

**Comment by kbower** [comment]
_**kbower** trac comment on Jan 10, 2011, 3:43:06 PM:_

We had this idea of our RMS supporting date and time for certain fields, where it makes sense, even though GERS currently can't.

For those fields, and only those fields, the mechanism is cfg.date_or_datetime.

cfg.now_func() will be compatible, but there are many fields that we don't want date and time.  Maybe deliverydate should only be a date. (period)

**Comment by kbower** [comment]
_**rneville** trac comment on Jan 10, 2011, 4:05:55 PM:_

(In [[1035]](../commit/4dd0189b0a5144b2b42522b8fedc4195b70eb174))
closes #534 (I think). Checked objects.py for any other similar timedelta calculations that might have to change and didn't find any with a quick search.

**Comment by kbower** [comment]
_**rneville** trac status change on Jan 10, 2011, 4:05:55 PM:_ **closed**
