### ISSUE TITLE
loadcustomerdata.py (Unable to acquire Oracle environment handle)

### ISSUE THREAD

**Issue by kbower** [kbower/tickettest1#583]
_Imported from trac ticket 583.
Created by **rneville**
Opened in trac: Jan 21, 2011, 11:00:47 PM
Last modified in trac: Jun 4, 2011, 8:48:56 AM_
***
_by rneville:_
fails on Oracle

**Comment by kbower** [comment]
_**kbower** trac comment on Jan 22, 2011, 7:15:36 AM:_

```
(tg2env)[rarch@kan admin]$ ./loadcustomerdata.py -r kan
loading datagenerators table...
Traceback (most recent call last):
  File "./loadcustomerdata.py", line 82, in <module>
    dependency_ordered_load(data[custname]['data'])
  File "/home/rarch/trunk/src/appserver/pylotengine/appsetup/dataload.py", line 286, in dependency_ordered_load
    load_static_data(tabledata.pop(table))
  File "/home/rarch/trunk/src/appserver/pylotengine/appsetup/dataload.py", line 381, in load_static_data
    if add_to_database(sa_obj):
  File "/home/rarch/trunk/src/appserver/pylotengine/appsetup/dataload.py", line 396, in add_to_database
    DBSession.flush()
  File "/home/rarch/tg2env/lib/python2.6/site-packages/SQLAlchemy-0.6.4.2kbdev-py2.6-linux-x86_64.egg/sqlalchemy/orm/scoping.py", line 132, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/home/rarch/tg2env/lib/python2.6/site-packages/SQLAlchemy-0.6.4.2kbdev-py2.6-linux-x86_64.egg/sqlalchemy/orm/session.py", line 1367, in flush
    self._flush(objects)
  File "/home/rarch/tg2env/lib/python2.6/site-packages/SQLAlchemy-0.6.4.2kbdev-py2.6-linux-x86_64.egg/sqlalchemy/orm/session.py", line 1448, in _flush
    flush_context.execute()
  File "/home/rarch/tg2env/lib/python2.6/site-packages/SQLAlchemy-0.6.4.2kbdev-py2.6-linux-x86_64.egg/sqlalchemy/orm/unitofwork.py", line 299, in execute
    rec.execute(self)
  File "/home/rarch/tg2env/lib/python2.6/site-packages/SQLAlchemy-0.6.4.2kbdev-py2.6-linux-x86_64.egg/sqlalchemy/orm/unitofwork.py", line 443, in execute
    uow
  File "/home/rarch/tg2env/lib/python2.6/site-packages/SQLAlchemy-0.6.4.2kbdev-py2.6-linux-x86_64.egg/sqlalchemy/orm/mapper.py", line 1594, in _save_obj
    connection = uowtransaction.transaction.connection(self)
  File "/home/rarch/tg2env/lib/python2.6/site-packages/SQLAlchemy-0.6.4.2kbdev-py2.6-linux-x86_64.egg/sqlalchemy/orm/session.py", line 247, in connection
    return self._connection_for_bind(engine)
  File "/home/rarch/tg2env/lib/python2.6/site-packages/SQLAlchemy-0.6.4.2kbdev-py2.6-linux-x86_64.egg/sqlalchemy/orm/session.py", line 307, in _connection_for_bind
    conn = self._parent._connection_for_bind(bind)
  File "/home/rarch/tg2env/lib/python2.6/site-packages/SQLAlchemy-0.6.4.2kbdev-py2.6-linux-x86_64.egg/sqlalchemy/orm/session.py", line 307, in _connection_for_bind
    conn = self._parent._connection_for_bind(bind)
  File "/home/rarch/tg2env/lib/python2.6/site-packages/SQLAlchemy-0.6.4.2kbdev-py2.6-linux-x86_64.egg/sqlalchemy/orm/session.py", line 318, in _connection_for_bind
    conn = bind.contextual_connect()
  File "/home/rarch/tg2env/lib/python2.6/site-packages/SQLAlchemy-0.6.4.2kbdev-py2.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1829, in contextual_connect
    self.pool.connect(), 
  File "/home/rarch/tg2env/lib/python2.6/site-packages/SQLAlchemy-0.6.4.2kbdev-py2.6-linux-x86_64.egg/sqlalchemy/pool.py", line 183, in connect
    return _ConnectionFairy(self).checkout()
  File "/home/rarch/tg2env/lib/python2.6/site-packages/SQLAlchemy-0.6.4.2kbdev-py2.6-linux-x86_64.egg/sqlalchemy/pool.py", line 370, in __init__
    rec = self._connection_record = pool.get()
  File "/home/rarch/tg2env/lib/python2.6/site-packages/SQLAlchemy-0.6.4.2kbdev-py2.6-linux-x86_64.egg/sqlalchemy/pool.py", line 214, in get
    return self.do_get()
  File "/home/rarch/tg2env/lib/python2.6/site-packages/SQLAlchemy-0.6.4.2kbdev-py2.6-linux-x86_64.egg/sqlalchemy/pool.py", line 733, in do_get
    con = self.create_connection()
  File "/home/rarch/tg2env/lib/python2.6/site-packages/SQLAlchemy-0.6.4.2kbdev-py2.6-linux-x86_64.egg/sqlalchemy/pool.py", line 148, in create_connection
    return _ConnectionRecord(self)
  File "/home/rarch/tg2env/lib/python2.6/site-packages/SQLAlchemy-0.6.4.2kbdev-py2.6-linux-x86_64.egg/sqlalchemy/pool.py", line 254, in __init__
    self.connection = self.__connect()
  File "/home/rarch/tg2env/lib/python2.6/site-packages/SQLAlchemy-0.6.4.2kbdev-py2.6-linux-x86_64.egg/sqlalchemy/pool.py", line 320, in __connect
    connection = self.__pool._creator()
  File "/home/rarch/tg2env/lib/python2.6/site-packages/SQLAlchemy-0.6.4.2kbdev-py2.6-linux-x86_64.egg/sqlalchemy/engine/strategies.py", line 76, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/rarch/tg2env/lib/python2.6/site-packages/SQLAlchemy-0.6.4.2kbdev-py2.6-linux-x86_64.egg/sqlalchemy/engine/default.py", line 249, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlalchemy.exc.InterfaceError: (InterfaceError) Unable to acquire Oracle environment handle None None
(tg2env)[rarch@kan admin]$ 

```

**Comment by kbower** [comment]
_**kbower** trac comment on Jan 22, 2011, 7:20:06 AM:_

The failure _(InterfaceError) Unable to acquire Oracle environment handle_ is while processing session, pooling, engine.  This is obviously not our software, though may be indirect result of us taking too many connections?

I believe those settings are development.ini/production.ini

**Comment by kbower** [comment]
_**kbower** trac comment on Feb 3, 2011, 10:38:53 AM:_

(Changeset [[1162]](../commit/404f88019ebf67658e7afb378ec8427e0eae3042))
 * comment that might fix the loadcustomerdata.py issue (see #583)

**Comment by kbower** [comment]
_**kbower** trac comment on Jun 4, 2011, 8:48:56 AM:_

It got better.

**Comment by kbower** [comment]
_**kbower** trac status change on Jun 4, 2011, 8:48:56 AM:_ **closed**
