### ISSUE TITLE
Print receipt crash related to not having financepromotion

### ISSUE THREAD

**Issue by kbower** [kbower/tickettest1#602]
_Imported from trac ticket 602.
Created by **kbower**
Opened in trac: Jan 26, 2011, 12:21:01 PM
Last modified in trac: Jan 26, 2011, 12:44:02 PM_
***
There was an error in generating the report you requested. Please see your system administrator and give them the following error message
Report 'receipt' caused the following exception: RError(u'Report \'receipt\' caused the following exception: UndefinedError(\'None has no member named "promotionid"\',)\nTraceback (most recent call last):\n File "/home/rarch/trunk/src/appserver/pylotengine/controllers/reports.py", line 97, in run\n htmldoc=render(output.template)\n File "/home/rarch/tg2env/lib/python2.6/site-packages/Pylons-0.9.7-py2.6.egg/pylons/templating.py", line 338, in render_genshi\n ns_options=(\'method\'), method=method)\n File "/home/rarch/tg2env/lib/python2.6/site-packages/Pylons-0.9.7-py2.6.egg/pylons/templating.py", line 249, in cached_template\n return render_func()\n File "/home/rarch/tg2env/lib/python2.6/site-packages/Pylons-0.9.7-py2.6.egg/pylons/templating.py", line 334, in render_template\n encoding=None))\n File "build/bdist.linux-x86_64/egg/genshi/core.py", line 179, in render\n return encode(generator, method=method, encoding=encoding, out=out)\n File "build/bdist.linux-x86_64/egg/genshi/output.py", line 60, in encode\n return _encode(u\'\'.join(list(iterator)))\n File "build/bdist.linux-x86_64/egg/genshi/output.py", line 311, in __call__\n for kind, data, pos in stream:\n File "build/bdist.linux-x86_64/egg/genshi/output.py", line 592, in __call__\n for kind, data, pos in stream:\n File "build/bdist.linux-x86_64/egg/genshi/output.py", line 698, in __call__\n for kind, data, pos in chain(stream, [(None, None, None)]):\n File "build/bdist.linux-x86_64/egg/genshi/output.py", line 532, in __call__\n for ev in stream:\n File "build/bdist.linux-x86_64/egg/genshi/core.py", line 283, in _ensure\n for event in stream:\n File "build/bdist.linux-x86_64/egg/genshi/template/base.py", line 569, in _include\n for event in stream:\n File "build/bdist.linux-x86_64/egg/genshi/template/markup.py", line 245, in _match\n for event in stream:\n File "build/bdist.linux-x86_64/egg/genshi/template/base.py", line 543, in _exec\n for event in stream:\n File "build/bdist.linux-x86_64/egg/genshi/template/base.py", line 496, in _eval\n for kind, data, pos in stream:\n File "build/bdist.linux-x86_64/egg/genshi/template/base.py", line 557, in _flatten\n **vars)\n File "build/bdist.linux-x86_64/egg/genshi/template/base.py", line 272, in _apply_directives\n stream = directives[0](iter(stream), directives[1:], ctxt, **vars)\n File "build/bdist.linux-x86_64/egg/genshi/template/directives.py", line 411, in __call__\n value = _eval_expr(self.expr, ctxt, **vars)\n File "build/bdist.linux-x86_64/egg/genshi/template/base.py", line 286, in _eval_expr\n retval = expr.evaluate(ctxt)\n File "build/bdist.linux-x86_64/egg/genshi/template/eval.py", line 180, in evaluate\n return eval(self.code, _globals, {\'__data__\': data})\n File "/home/rarch/trunk/src/appserver/pylotengine/templates/../../reports/receipt.html", line 359, in <Expression u"(c.receipt[0].originalfinanceamt or c.Decimal(\'0\')) > 0 and c.receipt[0].financepromotion.promotionid != None">\n <td class="financeinfo" colspan="4"><span py:if="(c.receipt[0].originalfinanceamt or c.Decimal(\'0\')) > 0 and c.receipt[0].financepromotion.promotionid != None">Fin. Promo. Code: ${c.receipt[0].financepromotion.promotionid}</span></td>\n File "build/bdist.linux-x86_64/egg/genshi/template/eval.py", line 321, in lookup_attr\n val = cls.undefined(key, owner=obj)\n File "build/bdist.linux-x86_64/egg/genshi/template/eval.py", line 405, in undefined\n raise UndefinedError(key, owner=owner)\nUndefinedError: None has no member named "promotionid"\n\n\n\n\n\n\n',) Traceback (most recent call last): File "/home/rarch/trunk/src/appserver/pylotengine/controllers/reports.py", line 101, in run raise RError("Report '%s' caused the following exception: %r\n%s\n\n\n\n\n\n" % (reportid, e, traceback.format_exc())) RError: Report 'receipt' caused the following exception: UndefinedError('None has no member named "promotionid"',) Traceback (most recent call last): File "/home/rarch/trunk/src/appserver/pylotengine/controllers/reports.py", line 97, in run htmldoc=render(output.template) File "/home/rarch/tg2env/lib/python2.6/site-packages/Pylons-0.9.7-py2.6.egg/pylons/templating.py", line 338, in render_genshi ns_options=('method'), method=method) File "/home/rarch/tg2env/lib/python2.6/site-packages/Pylons-0.9.7-py2.6.egg/pylons/templating.py", line 249, in cached_template return render_func() File "/home/rarch/tg2env/lib/python2.6/site-packages/Pylons-0.9.7-py2.6.egg/pylons/templating.py", line 334, in render_template encoding=None)) File "build/bdist.linux-x86_64/egg/genshi/core.py", line 179, in render return encode(generator, method=method, encoding=encoding, out=out) File "build/bdist.linux-x86_64/egg/genshi/output.py", line 60, in encode return _encode(u_.join(list(iterator))) File "build/bdist.linux-x86_64/egg/genshi/output.py", line 311, in __call__ for kind, data, pos in stream: File "build/bdist.linux-x86_64/egg/genshi/output.py", line 592, in __call__ for kind, data, pos in stream: File "build/bdist.linux-x86_64/egg/genshi/output.py", line 698, in __call__ for kind, data, pos in chain(stream, [(None, None, None)]): File "build/bdist.linux-x86_64/egg/genshi/output.py", line 532, in __call__ for ev in stream: File "build/bdist.linux-x86_64/egg/genshi/core.py", line 283, in _ensure for event in stream: File "build/bdist.linux-x86_64/egg/genshi/template/base.py", line 569, in _include for event in stream: File "build/bdist.linux-x86_64/egg/genshi/template/markup.py", line 245, in _match for event in stream: File "build/bdist.linux-x86_64/egg/genshi/template/base.py", line 543, in _exec for event in stream: File "build/bdist.linux-x86_64/egg/genshi/template/base.py", line 496, in _eval for kind, data, pos in stream: File "build/bdist.linux-x86_64/egg/genshi/template/base.py", line 557, in _flatten _**_vars) File "build/bdist.linux-x86_64/egg/genshi/template/base.py", line 272, in _apply_directives stream = directives[0](iter(stream), directives[1:], ctxt, **vars) File "build/bdist.linux-x86_64/egg/genshi/template/directives.py", line 411, in __call__ value = _eval_expr(self.expr, ctxt, **vars) File "build/bdist.linux-x86_64/egg/genshi/template/base.py", line 286, in _eval_expr retval = expr.evaluate(ctxt) File "build/bdist.linux-x86_64/egg/genshi/template/eval.py", line 180, in evaluate return eval(self.code, _globals, {'__data__': data}) File "/home/rarch/trunk/src/appserver/pylotengine/templates/../../reports/receipt.html", line 359, in <Expression u"(c.receipt[0].originalfinanceamt or c.Decimal('0')) > 0 and c.receipt[0].financepromotion.promotionid != None"> <td class="financeinfo" colspan="4"><span py:if="(c.receipt[0].originalfinanceamt or c.Decimal('0')) > 0 and c.receipt[0].financepromotion.promotionid != None">Fin. Promo. Code: ${c.receipt[0].financepromotion.promotionid}</span></td> File "build/bdist.linux-x86_64/egg/genshi/template/eval.py", line 321, in lookup_attr val = cls.undefined(key, owner=obj) File "build/bdist.linux-x86_64/egg/genshi/template/eval.py", line 405, in undefined raise UndefinedError(key, owner=owner) UndefinedError: None has no member named "promotionid" 
_

**Comment by kbower** [comment]
_**kbower** trac comment on Jan 26, 2011, 12:22:14 PM:_

Kent, I think this is the offending line...

<td class="financeinfo" colspan="4"><span py:if="(c.receipt[0].originalfinanceamt or c.Decimal('0')) > 0 and c.receipt[0].financepromotion.promotionid != None">Fin. Promo. Code: ${c.receipt[0].financepromotion.promotionid}</span></td>

I think the problem is the financepromotion object is None. Probably needs another and to check c.receipt[0].financepromotion

**Comment by kbower** [comment]
_**kbower** trac comment on Jan 26, 2011, 12:44:02 PM:_

(In [[1130]](../commit/971e09e466c8fff8bf2935396cbd864b4c50a09f))
 * fix printing receipt for financed orders without a financepromotion. fixes #602

**Comment by kbower** [comment]
_**kbower** trac status change on Jan 26, 2011, 12:44:02 PM:_ **closed**
