### ISSUE TITLE
Reservation rules

### ISSUE THREAD

**Issue by kentbower** [kbower/tickettest1#737]
_Imported from trac ticket 737.
Created by **rneville**
Opened in trac: Feb 23, 2011, 4:19:23 PM
Last modified in trac: May 26, 2011, 5:02:47 PM_
***
_
**From Rob:**
Salespeople really don't care about how many of SKU A is reserved on orders. What they really care about is "can I have a SKU A for my current order" and at the moment, they can't trust GERS when it says "no". So, let's fix it so that when the new system says "no", they know they can trust that's it's done all of the research that they would have to have done by hand for them.
It sounds to me like the system should be enforcing these business rules completely. We can incorporate all of those rules into several pieces of the system:
1. The fill process. This is kicked off as part of an Order save rule. So, we could_
    _a) not fill lines that fail to meet the criteria in your business rules from the beginning and_
    _b) we could automatically "steal" inventory from filled orders that do not meet the criteria in favor of the current order if it does meet the criteria (takes care of inventory reserved to orders not originally written in the new system that should otherwise be available to the current order)_
_2. The ATP logic such that it shows actual available merchandise availability, again according to whatever criteria you set forth._
----
I am in agreement with Mariam and Rob.  If the system can AUTOMATICALLY make "stealing" decisions based on company rules, then this should work.  For example, our rules consider the Written Date, Delivery Date, Delivery Destination (Exports), Deposit (payment) amounts, and incoming inventory.  If we can look at all of these, then this should work 99% of the time.

We will still need the option for the Sales Manager to go in and be able to analyze and "steal" whenever necessary, so this will not totally eliminate the need for a lookup screen anyway.  (For example, if we have a $99 chair reserved for a customer that is needed on a $10,000 order.  We could upgrade the $99 customer and satisfy the need of the $10,000 order.  (But this is an exception that only management should make.)

Thanks!
Jesús R Capó, VP, CIO 
----
We would like to filter what is 'considered' reserved.

1. Orders writen > 8 days ago with reserved inventory
2. Orders that are not scheduled for delivery (ZONE_CD = AVI)
3. Orders that are not for export. (Zone_cd <> 'EXP')
4. Order does not have 10% deposit (We can expand on this one if you need me to)

It sounds to me like the system should be enforcing these business rules completely. We can incorporate all of those rules into several pieces of the system:
1. The fill process. This is kicked off as part of an Order save rule. So, we could 
  a. not fill lines that fail to meet the criteria in your business rules from the beginning and
  b. we could automatically "steal" inventory from filled orders that do not meet the criteria in favor of the current order if it does meet the criteria (takes care of inventory reserved to orders not originally written in the new system that should otherwise be available to the current order)
2. The ATP logic such that it shows actual available merchandise availability, again according to whatever criteria you set forth.

**Comment by kentbower** [comment]
_**rneville** trac comment on Feb 25, 2011, 2:22:33 PM:_

adding Mariam as CC

**Comment by kentbower** [comment]
_**rneville** trac comment on May 10, 2011, 12:01:43 PM:_

As per JR...

You are absolutely correct in your assumptions.   BUT, currently they ARE required to use these Sort Codes.  They are pretty much disciplined in not using the Sort Codes improperly because other salespeople will catch it right away and remove the improper Sort Code and inform their respective managers.   When I said 80%, I meant the reverse of what you stated.  We will be removing 80% of the 100% that is available to remove.  Which means, we will be “stealing” LESS than what we should.  In other words, we will be pretty conservative if we only do the aforementioned agreed upon rules.

 

To give you some final food for thought: On a NIGHTLY basis, using SQL,  I currently use the SAME rules you will be writing to REMOVE inventory from orders.  The only difference between what I currently do and what you will be doing is that I remove inventory ONCE at midnight, while you will be doing it LIVE on the FLY on a per-needed basis.  In my case, I remove it from ALL ORDERS that qualify under these rules (whether I need the inventory or not).

 

Attn Robert:  On the DATE issue, you may INSTEAD look at the SHIP_TO_ZONE_CD.  We use “AVI” as the Zone Code for orders with No Dates or “Fake Dates”.  So currently, AVI is only used with the 12/31/29 Date, but if the Date ever changes, the ZONE_CD will continue to be: “AVI”.

 

Attn Robert:  I forgot to add Sort Code:  “OSP” as well to the “Protected Sort Codes List”. (Same as BAK, etc).  And I forgot to add “KEY” to the “Protected Delivery Zone Code List” (Same as OUT, etc)

 

Finally, just as an FYI, I run these SQL Statements EVERY NIGHT to make sure that Sort Codes are not misused:

 

This is used to REMOVE the "BAK" from orders that DO NOT QUALIFY for the protection of "BAK" Sort Code:

 

create table quicker as

select distinct a.del_doc_num del_doc_num

from so_ln b, so a

where a.del_doc_num = b.del_doc_num

and a.ord_srt_cd = 'BAK'

and a.ord_srt_cd <> 'OSP'

and a.stat_cd = 'O'

and b.picked <> 'X'

and b.itm_cd not like ('TPP%')

and b.loc_cd is not null

minus

select distinct a.del_doc_num del_doc_num

from so_ln b, so a

where a.del_doc_num = b.del_doc_num

and a.ord_srt_cd = 'BAK'

and a.ord_srt_cd <> 'OSP'

and a.stat_cd = 'O'

and b.picked <> 'X'

and b.itm_cd not like ('TPP%')

and b.loc_cd is null

/

create table quicker2 as

select distinct a.del_doc_num del_doc_num

from quicker a, so_ln b

where a.del_doc_num = b.del_doc_num

and b.fill_dt < sysdate-4

minus

select distinct a.del_doc_num del_doc_num

from quicker a, so_ln b

where a.del_doc_num = b.del_doc_num

and b.fill_dt >= sysdate-4

/

update so

set ord_srt_cd = 'COD'

where ord_srt_cd = 'BAK'

and ord_srt_cd <> 'OSP'

and del_doc_num in

(select del_doc_num

from quicker2)

/

drop table quicker

/

drop table quicker2

/

 

Here I verify that if an order has "VIP" protection on it, that it is a valid "VIP"  (Paid in Full):

 

create table paid_orders as

select ivc_cd, sum(decode(trn_tp_cd,'DEP',-1*(AMT),'DTC',-1*(AMT),'DTD',+1*(AMT)

,'PMT',-1*(AMT),'SAL',+1*(AMT))) Total

from ar_trn

where ivc_cd in

(select del_doc_num

from so

where stat_cd = 'O'

and ship_to_zone_cd = 'VIP'

and ord_srt_cd <> 'OSP'

and ord_tp_cd = 'SAL')

group by ivc_cd

/

update so

set ship_to_zone_cd = 'AVI'

where ship_to_zone_cd = 'VIP'

and ord_tp_cd = 'SAL'

and stat_cd = 'O'

and ORD_SRT_CD not in ('BAK','OSP')

and del_doc_num in

(select ivc_cd

from paid_orders

where total > 0)

/

**Comment by kentbower** [comment]
_**rneville** trac comment on May 10, 2011, 1:47:57 PM:_

On Tue, May 3, 2011 at 10:51 AM, Jesus Capo <Jesus@eldoradofurniture.com> wrote:

    As an alternative to OOSL, we believe the following rule will resolve 80% of the need to lookup reserved inventory:

     

    After not being available in ITM_FIFL, we should look at and remove inventory from sales order that meet the following criteria:

     

    Part One (for now):

     

    If an order was written Over 8 Days ago, 

 
assume I'm looking at SO.SO_WR_DT ?

    AND it has NO Scheduled Delivery Date


since this is a not-null field, I assume that this really means there's no "real" delivery date. In which case, I need to know all of the "not real" delivery dates you use and while we're at it, what those "fake" delivery dates mean business-wise to El Dorado. That way we can setup human readable statuses for those dates. I think we have one right now (12/2049 or something). If that's the only one such that we're saying pu_del_dt == 12/2049, let me know.
 

    AND it is NOT Attached to TRK_STOP

OK
 

    AND Ship_to_Zone_Code <> 'TMA','EXP','ORL','OUT'(Maximum of 30 days from Written)

OK
 

    AND SORT_CD <> 'VIP' (Maximum of 30 days from Written)

OK

    AND SORT_CD <> 'BAK' (No Maximum number of days)

OK

     

    (Where it says “Maximum of 30 Days from Written”, this means that the inventory on these orders CANNOT BE REMOVED until 30 Days AFTER they have been written)

     

    Part Two (for later? Or Now if possible):

     

    1.       No matter when it was written, if an order does NOT have at least a 10% deposit (includes credit from a voided order, credit memo, payments, etc), then we can remove inventory.

Be careful :) us programmers have a way of interpreting what you say literally LOL...when you say "no matter when it was written", does this mean that this rule should override all other rules? For example, if sort code = 'BAK' but there's not at least a 10% deposit, then it's OK to take it?

How to calculate 10% deposit when we're including credit from voided orders, crm's etc can get tricky. Am I simply adding up all credits against an IVC_CD and comparing that to .10 x the SAL transaction amt?

     

    2.       If an order has NEVER had inventory attached to it, but now it does, we give it 5 days from fill date BEFORE removing inventory.

I don't see how to determine this reliably without referencing history transactions...as a rule it's typically a bad idea to base functionality off of history records...the code is always very fragile and error prone and can be expensive in terms of DB interaction. We could add additional fields to our order line table that could track whether a line had ever been filled or not and we could keep track of it but that only works if all filling and unfilling happened via our system, which it wont be and hasn't been so this would break for the majority of your orders.

Just doing a simple little query like this:
SQL> select count(*) from inventorytrans
  2  where orderid = '0414809IFBC'
  3  and type = 'OOR'
  4  and productid = '521720804';

  COUNT(*)
----------
     6

took more than 1s to come back....if we expand this to lots of orders? Just saying performance may become an issue here.

     

    3.       If an order is partially filled, and ALL the items are the SAME Minor Code, but is still missing inventory, the 5 days begin to count when the ENTIRE order is filled. 

Same caveat as last one...performance concerns about doing this en masse.

     

     

    If you have any questions, please let me know.


General comments / questions....

Since you put the 5 day thing in the "later" portion of this, are we saying that it's ok to live with the consequences of implementing the other rules without those rules in place? The reason I bring this up is that the effect may not be something you're willing to go live with....basically it means that we will end up:
a) stealing inventory from an order written 15 days ago, never had inventory attached to it, but now it does
b) honoring reservations against orders with insufficient deposits and not stealing when we should

To me, this seems like an all-or-nothing scenario but then I don't have a grasp for how often these things come up and what the fallout would be of scenario a or b so your call, just want to make sure we've thought about a bit first.

**Comment by kentbower** [comment]
_**rneville** trac comment on May 10, 2011, 1:48:26 PM:_

On Tue, May 3, 2011 at 10:51 AM, Jesus Capo <Jesus@eldoradofurniture.com> wrote:

As an alternative to OOSL, we believe the following rule will resolve 80% of the need to lookup reserved inventory:

 

After not being available in ITM_FIFL, we should look at and remove inventory from sales order that meet the following criteria:

 

Part One (for now):

 

If an order was written Over 8 Days ago,

 

assume I'm looking at SO.SO_WR_DT ?  YES

    AND it has NO Scheduled Delivery Date


since this is a not-null field, I assume that this really means there's no "real" delivery date. In which case, I need to know all of the "not real" delivery dates you use and while we're at it, what those "fake" delivery dates mean business-wise to El Dorado. That way we can setup human readable statuses for those dates. I think we have one right now (12/2049 or something). If that's the only one such that we're saying pu_del_dt == 12/2049, let me know.

 

We only have ONE “Fake” delivery date:  12/31/29 (used to be 12/31/49 – so we could have BOTH programmed)


 

    AND it is NOT Attached to TRK_STOP

OK  OK
 

    AND Ship_to_Zone_Code <> 'TMA','EXP','ORL','OUT'(Maximum of 30 days from Written)

OK  OK
 

    AND SORT_CD <> 'VIP' (Maximum of 30 days from Written)

OK   OK

    AND SORT_CD <> 'BAK' (No Maximum number of days)

OK   OK

     

    (Where it says “Maximum of 30 Days from Written”, this means that the inventory on these orders CANNOT BE REMOVED until 30 Days AFTER they have been written)

     

    Part Two (for later? Or Now if possible):

     

    1.       No matter when it was written, if an order does NOT have at least a 10% deposit (includes credit from a voided order, credit memo, payments, etc), then we can remove inventory.

Be careful :) us programmers have a way of interpreting what you say literally LOL...when you say "no matter when it was written", does this mean that this rule should override all other rules? For example, if sort code = 'BAK' but there's not at least a 10% deposit, then it's OK to take it?

How to calculate 10% deposit when we're including credit from voided orders, crm's etc can get tricky. Am I simply adding up all credits against an IVC_CD and comparing that to .10 x the SAL transaction amt?

     You are very astute in your questions!  Now that I think about it, I forgot to mention approved “FINANCED ORDERS” with ZERO deposits and customers who have CASHIER CHECKS that are being processed, and pending Credit Memos, etc.  So for NOW, let’s not touch this.  Too many permutations…

    2.       If an order has NEVER had inventory attached to it, but now it does, we give it 5 days from fill date BEFORE removing inventory.

I don't see how to determine this reliably without referencing history transactions...as a rule it's typically a bad idea to base functionality off of history records...the code is always very fragile and error prone and can be expensive in terms of DB interaction. We could add additional fields to our order line table that could track whether a line had ever been filled or not and we could keep track of it but that only works if all filling and unfilling happened via our system, which it wont be and hasn't been so this would break for the majority of your orders.

Just doing a simple little query like this:
SQL> select count(*) from inventorytrans
  2  where orderid = '0414809IFBC'
  3  and type = 'OOR'
  4  and productid = '521720804';

  COUNT(*)
----------
     6

took more than 1s to come back.....if we expand this to lots of orders? Just saying performance may become an issue here.

     I agree that this will have an impact.  Again, let’s put this one on HOLD and see how it goes with the other rules.

    3.       If an order is partially filled, and ALL the items are the SAME Minor Code, but is still missing inventory, the 5 days begin to count when the ENTIRE order is filled.

Same caveat as last one...performance concerns about doing this en masse.   SAME AS ABOVE

     

     

    If you have any questions, please let me know.


General comments / questions....

Since you put the 5 day thing in the "later" portion of this, are we saying that it's ok to live with the consequences of implementing the other rules without those rules in place? The reason I bring this up is that the effect may not be something you're willing to go live with....basically it means that we will end up:
a) stealing inventory from an order written 15 days ago, never had inventory attached to it, but now it does
b) honoring reservations against orders with insufficient deposits and not stealing when we should

To me, this seems like an all-or-nothing scenario but then I don't have a grasp for how often these things come up and what the fallout would be of scenario a or b so your call, just want to make sure we've thought about a bit first.

 

If we put the appropriate SORT CODES (BAK, VIP, etc) on the orders, then it would not matter.  Those orders that have partial inventory allocated are supposed to have a “BAK” sort code attached to them (letting everyone know that they are “protected” from being removed).  I was trying to avoid having to manually add sort codes to flag orders, but we may have to continue.  (One thing we WILL need are MULTIPLE SORT CODES on the same order, which does not currently exist).

**Comment by kentbower** [comment]
_**rneville** trac comment on May 10, 2011, 1:48:44 PM:_

Multiple sort codes? Yikes...like I said the day before...these rules have a nasty way of creeping into complexity ;)

To save a lot of typing, let's just say that you can't have multiple sort codes (yet). That'd be tricky to implement (and impossible in the time-frame) and there's no way for people writing orders in GERS to apply multiple sort codes and it doesn't address the population of existing orders that might have inventory stolen from it erroneously.

There's really only two, right? VIP and BAK. That doesn't sound too bad.

It may be a good first pass at this to continue to use sort codes and down the road, tackle rules to automatically apply sort codes.

We'll give it a go then with the "approved" rules in this email thread...

**Comment by kentbower** [comment]
_**rneville** trac comment on May 10, 2011, 1:48:56 PM:_

Perfect! 

What I meant about multiple Sort Codes was for FUTURE enhancements, not for this go round.  Mostly because GERS only accepts ONE sort code.

 

Thanks,

JR

**Comment by kentbower** [comment]
_**rneville** trac comment on May 10, 2011, 1:49:15 PM:_

My concern about the "80% there" is what I think Rob was articulating here, but I need to be very clear.

We are not saying "the system will make the best guess and 80% of the time we will take inventory from other orders when we are allowed to."  Unfortunately, what it seems to me we are saying is "make your best guess and 80% of the time you will be right".  This implies that the other 20% of the time we will be taking inventory that we cannot be touching (including, of course, orders that the new POS didn't write and never even touched).  It isn't fail safe.

Even if we are ok with this, my concern is the perception of the new users (and especially those who aren't even using the system yet), "that stupid new system stole my inventory and it wasn't allowed to" and seeing this as bugs in the system (not to mention angry customers).

Are salespeople currently required to use these special sort codes?  In other words, in the cases we steal inventory and shouldn't have will it be the salesperson's fault for not having the correct sort code?  Ultimately the system should be smart enough to decide these rules without any sort code.  In fact, the sort code should only be for cases where the salesperson needs to tell the system something it can't otherwise figure out (like "customer wants floor sample"), but we aren't able to get that sophisticated my Monday...

If they are currently required to use these sort codes, what stops salespeople from holding their inventory by using one of these sort codes when they shouldn't?

**Comment by kentbower** [comment]
_**rneville** trac comment on May 12, 2011, 8:49:09 AM:_

(Changeset [[1447]](../commit/0b5b837207db251f2531e26cb1c93160deaf8f4c))
addresses #737 (Reservation rules). This should take care of "stealing" illegal inventory reservations for all cases outlined by Eldorado, except for the 10% deposit rule since the definition for that is not fully done yet.

**Comment by kentbower** [comment]
_**rneville** trac comment on May 12, 2011, 8:50:53 AM:_

This may get closed later since testing this is very difficult without live data, so instead I'm dropping the priority way down...

**Comment by kentbower** [comment]
_**rneville** trac comment on May 18, 2011, 4:40:37 PM:_

(Changeset [[1478]](../commit/a1254cc3a2e6bd5076feb3d0e5f54ea8b9d32614))
 * fixes issue where unreserve_inventory() would fail because load_originals had not been called, see #737 [reservation "stealing"]

**Comment by kentbower** [comment]
_**kbower** trac comment on May 21, 2011, 10:26:36 AM:_

Tried to add a MORG6 package to an existing order:
```
A fatal error was encountered when communicating with the server.

Server Debug is enabled, output can be found here:
https://dev/tg/_debug/view/1305987643

Error message:
RError: Order Rule 'auto_fill_orders' caused the following exception: RuntimeError('maximum recursion depth exceeded in __instancecheck__',)
Traceback (most recent call last):
  File "/home/rarch/trunk/src/appserver/pylotengine/model/objects.py", line 6068, in run_save_rules
    stop_rules = scope['__rule_fn__']()
  File "auto_fill_orders", line 72, in __rule_fn__
  File "auto_fill_orders", line 44, in illegal_filled_order_lines
  File "/home/rarch/trunk/src/appserver/pylotengine/model/objects.py", line 606, in _load_originals
    get_obj._set_original()
  File "/home/rarch/trunk/src/appserver/pylotengine/model/objects.py", line 561, in _set_original
    item._set_original()
  File "/home/rarch/trunk/src/appserver/pylotengine/model/objects.py", line 4277, i ...
```

**Comment by kentbower** [comment]
_**kbower** trac comment on May 23, 2011, 1:48:12 AM:_

This problem will prevent go live, setting as blocker...

**Comment by kentbower** [comment]
_**rneville** trac comment on May 24, 2011, 8:49:24 AM:_

(Changeset [[1514]](../commit/1c5c4c6ede895432ab596a1c48dc320a2eee399e))
 * addresses #737 Reservation rules

**Comment by kentbower** [comment]
_**kbower** trac comment on May 25, 2011, 5:29:24 PM:_

(Changeset [[1520]](../commit/9691cf7072ad1357961853c75f358c60a1e05339))
 * several fixes for eld reservation rules (addresses #737)
   * note that there is still unreachable logic, so turning back to Rob
   * 'AVI' apparently replaces logic for needing to check deliverydate, but something just seems off that we never need to once check deliverydate.?

**Comment by kentbower** [comment]
_**rneville** trac comment on May 26, 2011, 4:30:48 PM:_

there's was as indentation problem that was causing the unreachable logic unless I'm missing something else?? I think this can be closed for now until we get further instructions or more refined rules from them.

I asked about checking the actual date and JR insisted that checking 'AVI' was better...so see no reason to do otherwise.

**RECOMMEND WE CLOSE THIS**

**Comment by kentbower** [comment]
_**rneville** trac status change on May 26, 2011, 5:02:47 PM:_ **closed**
