### ISSUE TITLE
Discount recalculations cause itemprice update statements even if they ultimately recalculate the same.

### ISSUE THREAD

**Issue by kbower** [kbower/tickettest1#841]
_Imported from trac ticket 841.
Created by **kbower**
Opened in trac: Mar 31, 2011, 12:07:39 PM
Last modified in trac: Sep 21, 2012, 5:13:51 PM_
***
This can cause error: Cannot change 'itemprice' if the line's added date is prior to the site's last balance date (03/23/2011)

-------- Original Message --------
Subject:         Fatal Error
Date:         Thu, 31 Mar 2011 11:29:46 -0400
From:         Wayne Liburd <wlibur@kanesfurniture.com>
To:         Kent Bower <kb@retailarchitects.com>, Rob Neville <rn@retailarchitects.com>

Kent or Rob,

Could you take a look at the following error?

Just received this error. We added comments to SO# 0312116JI94 and were attempting to save the changes. No other changes were made to the order.

A fatal error was encountered when communicating with the server.

Server Debug is enabled, output can be found here:
https://kanes.retailarchitects.com/tg/_debug/view/1301580149

Error message:
RError: System Rule 'Order.process_totaldiscount' caused the following exception: RError(u'System Rule \'OrderDetailDiscount.process_applies\' caused the following exception: RError("Cannot change \'itemprice\' if the line\'s added date is prior to the site\'s last balance date (03/23/2011)",)\nTraceback (most recent call last):\n  File "/home/rarch/trunk/src/appserver/pylotengine/model/objects.py", line 5939, in system_rule_allow_none\n    return params[\'__rule_fn__\']()\n  File "OrderDetailDiscount.process_applies", line 114, in __rule_fn__\n  File "OrderDetailDiscount.process_applies", line 61, in exclusions_a\n  File "/home/rarch/tg2env/lib/python2.6/site-packages/SQLAlchemy-0.6.4.3kbdev-py2.6-linux-x86_64. ...

Thanks,

*Wayne Liburd*

**Comment by kbower** [comment]
_**kbower** trac comment on Sep 23, 2011, 8:45:18 AM:_

See also [#1091](1091)

**Comment by kbower** [comment]
_**kbower** trac comment on Sep 21, 2012, 12:51:13 PM:_

Bizarre as this is, a discount framework issue is blocking the v12 inventory port changes, and fixing that issue, should, by side effect, also fix this ticket.

**Comment by kbower** [comment]
_**kbower** trac comment on Sep 21, 2012, 5:13:51 PM:_

(Changeset [[3186]](../commit/5ca27bd5097536f93304fe125131daa543b81146))
 * disable autoflush during discount calculations. fixes #841 (Discount recalculations cause itemprice update statements even if they ultimately recalculate the same.)

**Comment by kbower** [comment]
_**kbower** trac status change on Sep 21, 2012, 5:13:51 PM:_ **closed**
