### ISSUE TITLE
NotImplementedError: We haven't implemented changing a package product

### ISSUE THREAD

**Issue by kbower** [kbower/tickettest1#849]
_Imported from trac ticket 849.
Created by **kbower**
Opened in trac: Apr 7, 2011, 4:18:42 PM
Last modified in trac: Jun 4, 2011, 12:49:47 PM_
***
_by kbower:_
**Somehow someone was able to change the productid of a package! **

Here is the evidence:  (hit Preview and you can see this without scrolling)
```
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228] Error - <class 'pylotengine.RError'>: System Rule 'Order.process_package_lines' caused the following exception: NotImplementedError("We haven't implemented changing a package product",)
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228] Traceback (most recent call last):
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228]   File "/home/rarch/trunk/src/appserver/pylotengine/model/objects.py", line 5946, in system_rule_allow_none
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228]     return params['__rule_fn__']()
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228]   File "Order.process_package_lines", line 3, in __rule_fn__
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228]   File "/home/rarch/trunk/src/appserver/pylotengine/model/autoupdate.py", line 106, in override_with_rule
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228]     retval = process()
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228]   File "/home/rarch/trunk/src/appserver/pylotengine/model/autoupdate.py", line 104, in process
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228]     return fn(self)
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228]   File "/home/rarch/trunk/src/appserver/pylotengine/model/objects.py", line 2724, in process_package_lines
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228]     raise NotImplementedError("We haven't implemented changing a package product")
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228] NotImplementedError: We haven't implemented changing a package product
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228]
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228] Exception in supplement:
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228] Traceback (most recent call last):
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228]   File "/home/rarch/tg2env/lib/python2.6/site-packages/WebError-0.10.1-py2.6.egg/weberror/collector.py", line 295, in collectLine
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228]     data['supplement'] = self.collectSupplement(supp, tb)
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228]   File "/home/rarch/tg2env/lib/python2.6/site-packages/WebError-0.10.1-py2.6.egg/weberror/collector.py", line 257, in collectSupplement
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228]     result['extra'] = func()
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228]   File "/home/rarch/tg2env/lib/python2.6/site-packages/WebError-0.10.1-py2.6.egg/weberror/errormiddleware.py", line 310, in extraData
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228]     if name.upper() == name:
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228] AttributeError: 'symbol' object has no attribute 'upper'
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228]
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228] File '/home/rarch/tg2env/lib/python2.6/site-packages/WebError-0.10.1-py2.6.egg/weberror/errormiddleware.py', line 162 in __call__
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228]   app_iter = self.application(environ, sr_checker)
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228] File '/home/rarch/tg2env/lib/python2.6/site-packages/TurboGears2-2.0.1.1kb-py2.6.egg/tg/configuration.py', line 643 in wrapper
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228]   return app(environ, start_response)
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228] File '/home/rarch/tg2env/lib/python2.6/site-packages/TurboGears2-2.0.1.1kb-py2.6.egg/tg/configuration.py', line 543 in remover
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228]   return app(environ, start_response)
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228] File '/home/rarch/tg2env/lib/python2.6/site-packages/repoze.tm2-1.0a4-py2.6.egg/repoze/tm/__init__.py', line 19 in __call__
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228]   result = self.application(environ, save_status_and_headers)
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228] File '/home/rarch/tg2env/lib/python2.6/site-packages/repoze.who-1.0.10-py2.6.egg/repoze/who/middleware.py', line 107 in __call__
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228]   app_iter = app(environ, wrapper.wrap_start_response)
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228] File '/home/rarch/trunk/src/appserver/pylotengine/custom_middleware/tranlog.py', line 45 in __call__
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228]   ret = self.app(environ,start_response)
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228] File '/home/rarch/tg2env/lib/python2.6/site-packages/ToscaWidgets-0.9.7.1-py2.6.egg/tw/core/middleware.py', line 36 in __call__
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228]   return self.wsgi_app(environ, start_response)
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228] File '/home/rarch/tg2env/lib/python2.6/site-packages/ToscaWidgets-0.9.7.1-py2.6.egg/tw/core/middleware.py', line 59 in wsgi_app
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228]   resp = req.get_response(self.application)
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228] File 'build/bdist.linux-x86_64/egg/webob/__init__.py', line 1325 in get_response
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228] File 'build/bdist.linux-x86_64/egg/webob/__init__.py', line 1293 in call_application
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228] File '/home/rarch/tg2env/lib/python2.6/site-packages/ToscaWidgets-0.9.7.1-py2.6.egg/tw/core/resource_injector.py', line 67 in _injector
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228]   resp = req.get_response(app)
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228] File 'build/bdist.linux-x86_64/egg/webob/__init__.py', line 1325 in get_response
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228] File 'build/bdist.linux-x86_64/egg/webob/__init__.py', line 1293 in call_application
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228] File '/home/rarch/tg2env/lib/python2.6/site-packages/Beaker-1.3.1-py2.6.egg/beaker/middleware.py', line 70 in __call__
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228]   return self.app(environ, start_response)
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228] File '/home/rarch/tg2env/lib/python2.6/site-packages/Beaker-1.3.1-py2.6.egg/beaker/middleware.py', line 149 in __call__
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228]   return self.wrap_app(environ, session_start_response)
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228] File '/home/rarch/tg2env/lib/python2.6/site-packages/Routes-1.10.3-py2.6.egg/routes/middleware.py', line 130 in __call__
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228]   response = self.app(environ, start_response)
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228] File '/home/rarch/tg2env/lib/python2.6/site-packages/Pylons-0.9.7-py2.6.egg/pylons/wsgiapp.py', line 125 in __call__
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228]   response = self.dispatch(controller, environ, start_response)
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228] File '/home/rarch/tg2env/lib/python2.6/site-packages/Pylons-0.9.7-py2.6.egg/pylons/wsgiapp.py', line 324 in dispatch
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228]   return controller(environ, start_response)
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228] File '/home/rarch/trunk/src/appserver/pylotengine/lib/base.py', line 67 in __call__
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228]   return TGController.__call__(self, environ, start_response)
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228] File '/home/rarch/tg2env/lib/python2.6/site-packages/Pylons-0.9.7-py2.6.egg/pylons/controllers/core.py', line 221 in __call__
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228]   response = self._dispatch_call()
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228] File '/home/rarch/tg2env/lib/python2.6/site-packages/Pylons-0.9.7-py2.6.egg/pylons/controllers/core.py', line 172 in _dispatch_call
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228]   response = self._inspect_call(func)
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228] File '/home/rarch/tg2env/lib/python2.6/site-packages/Pylons-0.9.7-py2.6.egg/pylons/controllers/core.py', line 107 in _inspect_call
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228]   result = self._perform_call(func, args)
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228] File '/home/rarch/tg2env/lib/python2.6/site-packages/TurboGears2-2.0.1.1kb-py2.6.egg/tg/controllers.py', line 835 in _perform_call
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228]   self, controller, params, remainder=remainder)
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228] File '/home/rarch/tg2env/lib/python2.6/site-packages/TurboGears2-2.0.1.1kb-py2.6.egg/tg/controllers.py', line 172 in _perform_call
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228]   output = controller(*remainder, **dict(params))
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228] File '/home/rarch/trunk/src/appserver/pylotengine/controllers/__init__.py', line 14 in expose_ie_json_decorator
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228]   retval = func(*args, **params)
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228] File '/home/rarch/trunk/src/appserver/pylotengine/controllers/dbentity.py', line 344 in get_updates
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228]   response.results.append(run_updates(sa_obj, changeset, also_managing))
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228] File '/home/rarch/trunk/src/appserver/pylotengine/model/autoupdate.py', line 424 in run_updates
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228]   run_updates_obj(transfer_obj, client_changeset)
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228] File '/home/rarch/trunk/src/appserver/pylotengine/model/autoupdate.py', line 397 in run_updates_obj
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228]   method.method(obj)
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228] File '/home/rarch/trunk/src/appserver/pylotengine/model/autoupdate.py', line 106 in override_with_rule
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228]   retval = process()
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228] File '/home/rarch/trunk/src/appserver/pylotengine/model/autoupdate.py', line 101 in process
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228]   return cfg.system_rule_allow_none(rule_name % classname, **params)
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228] File '/home/rarch/trunk/src/appserver/pylotengine/model/objects.py', line 5950 in system_rule_allow_none
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228]   raise RError("System Rule '%s' caused the following exception: %r\\n%s" % (rulename, e, traceback.format_exc()))
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228] RError: System Rule 'Order.process_package_lines' caused the following exception: NotImplementedError("We haven't implemented changing a package product",)
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228] Traceback (most recent call last):
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228]   File "/home/rarch/trunk/src/appserver/pylotengine/model/objects.py", line 5946, in system_rule_allow_none
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228]     return params['__rule_fn__']()
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228]   File "Order.process_package_lines", line 3, in __rule_fn__
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228]   File "/home/rarch/trunk/src/appserver/pylotengine/model/autoupdate.py", line 106, in override_with_rule
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228]     retval = process()
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228]   File "/home/rarch/trunk/src/appserver/pylotengine/model/autoupdate.py", line 104, in process
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228]     return fn(self)
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228]   File "/home/rarch/trunk/src/appserver/pylotengine/model/objects.py", line 2724, in process_package_lines
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228]     raise NotImplementedError("We haven't implemented changing a package product")
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228] NotImplementedError: We haven't implemented changing a package product
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228]
[Thu Apr 07 12:41:13 2011] [error] [client 173.221.136.228] ------------------------------------------------------------
```

**Comment by kbower** [comment]
_**kbower** trac comment on Jun 4, 2011, 12:47:19 PM:_

false alarm, this error is correctly hit when a user attempts to change a package component into another package.

**Comment by kbower** [comment]
_**kbower** trac status change on Jun 4, 2011, 12:47:36 PM:_ **closed**

**Comment by kbower** [comment]
_**kbower** trac comment on Jun 4, 2011, 12:49:47 PM:_

opened [#943](943)
