### ISSUE TITLE
Re: FW: New POS System Error

### ISSUE THREAD

**Issue by kbower** [kbower/tickettest1#868]
_Imported from trac ticket 868.
Created by **rneville**
Opened in trac: Apr 29, 2011, 2:11:20 PM
Last modified in trac: Apr 29, 2011, 2:42:36 PM_
***
_by rneville:_
Hmmm, that is odd...

The error message is from Python.....which I can reproduce quite easily

Python 2.6.2 (r262:71600, Jan  5 2010, 11:14:35)
[GCC 4.1.2 20080704 (Red Hat 4.1.2-46)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: invalid literal for int() with base 10: '1234j'

And
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: invalid literal for int() with base 10: _
_
We're obviously dealing with scenario #2 here which means that we passed an
empty string somewhere that we tried to convert to an integer...

My strong suspicion is that this happened in the mod10 check area of the
code where we're integrity checking the account number that was entered for
a financed sale. We'll look at it...there's no way to know now, but it would
have been useful had we known what they typed/fat-fingered into the account
number field...oh well.

Thanks!

On Fri, Apr 29, 2011 at 1:51 PM, Alexander Harvey <aharve@kanesfurniture.com

**Comment by kbower** [comment]
_**kbower** trac status change on Apr 29, 2011, 2:40:37 PM:_ **closed**

**Comment by kbower** [comment]
_**kbower** trac comment on Apr 29, 2011, 2:40:38 PM:_

Closed as duplicate of #832.

**Comment by kbower** [comment]
_**kbower** trac comment on Apr 29, 2011, 2:42:36 PM:_

This occurs when someone adds a nonnumeric character to the account number.  https://trac.retailarchitects.com:444/trac/ticket/832
