### ISSUE TITLE
Receipt error

### ISSUE THREAD

**Issue by kbower** [kbower/tickettest1#902]
_Imported from trac ticket 902.
Created by **kbower**
Opened in trac: May 23, 2011, 3:39:45 PM
Last modified in trac: May 23, 2011, 3:53:12 PM_
***
_by kbower:_
Report 'receipt' caused the following exception: RError(u'Datagenerator \'receipt\' caused the following exception: KeyError(\'orderid\',)\nTraceback (most recent call last):\n File "/home/rarch/trunk/src/appserver/pylotengine/model/objects.py", line 7018, in run\n exec generator in scope #args will be in scope and thus usable in the data generator code\n File "<string>", line 1, in <module>\nKeyError: \'orderid\'\n',) Traceback (most recent call last): File "/home/rarch/trunk/src/appserver/pylotengine/controllers/reports.py", line 54, in run r = generator.run(kwargs) File "/home/rarch/trunk/src/appserver/pylotengine/model/objects.py", line 7024, in run raise RError("Datagenerator '%s' caused the following exception: %r\n%s" % (self.name, e, traceback.format_exc())) RError: Datagenerator 'receipt' caused the following exception: KeyError('orderid',) Traceback (most recent call last): File "/home/rarch/trunk/src/appserver/pylotengine/model/objects.py", line 7018, in run exec generator in scope #args will be in scope and thus usable in the data generator code File "<string>", line 1, in <module> KeyError: 'orderid'

Thanks!

Mariam H. Farach

Project Manager

El Dorado Furniture

corp. offices: 4200 NW 167^th St., Miami Gardens, FL, 33054

direct: 305.624.9700 ext. 55411

e-mail: mariam@eldoradofurniture.com

Visit us online! www.eldoradofurniture.com http://www.eldoradofurniture.com/

**Comment by kbower** [comment]
_**kbower** trac comment on May 23, 2011, 3:53:12 PM:_

Data was not set up to be loaded properly.

**Comment by kbower** [comment]
_**kbower** trac status change on May 23, 2011, 3:53:12 PM:_ **closed**
