### ISSUE TITLE
Kane's discounts cause autoupdate crash when adding package after discount

### ISSUE THREAD

**Issue by kbower** [kbower/tickettest1#928]
_Imported from trac ticket 928.
Created by **kbower**
Opened in trac: May 31, 2011, 12:24:34 PM
Last modified in trac: May 31, 2011, 12:42:39 PM_
***
RError(u'System Rule \'OrderDetailDiscount.process_applies\' caused the following exception: AttributeError("\'OrderDetail\' object has no attribute \'passed_line_obj\'",)\nTraceback (most recent call last):\n File "/home/rarch/trunk/src/appserver/pylotengine/model/objects.py", line 6152, in system_rule_allow_none\n return params[\'__rule_fn__\']()\n File "OrderDetailDiscount.process_applies", line 95, in __rule_fn__\n File "OrderDetailDiscount.process_applies", line 75, in exclusive_exclusions_b\n File "OrderDetailDiscount.process_applies", line 73, in exclusions_b\n File "app_startup", line 387, in kanes_discountexcluded_b\n File "/home/rarch/trunk/src/appserver/pylotengine/model/objects.py", line 102, in __getattr__\n raise AttributeError("\'%s\' object has no attribute \'%s\'" % (self.__class__.__name__, name))\nAttributeError: \'OrderDetail\' object has no attribute \'passed_line_obj\'\n',) Traceback (most recent call last): File "/home/rarch/trunk/src/appserver/pylotengine/model/objects.py", line 6152, in system_rule_allow_none return params['__rule_fn__']() File "Order.process_totaldiscount", line 11, in __rule_fn__ File "/home/rarch/trunk/src/appserver/pylotengine/model/autoupdate.py", line 107, in override_with_rule retval = process() File "/home/rarch/trunk/src/appserver/pylotengine/model/autoupdate.py", line 105, in process return fn(self) File "/home/rarch/trunk/src/appserver/pylotengine/model/objects.py", line 3983, in process_totaldiscount applicable_disc, self._linepricestotal_, self._linecoststotal_ = l.add_discount_record(discount, False) File "/home/rarch/trunk/src/appserver/pylotengine/model/objects.py", line 5319, in add_discount_record if linediscount.applies == u'Y': File "/home/rarch/trunk/src/appserver/pylotengine/model/objects.py", line 96, in __getattr__ rule_prop_method.method(self) File "/home/rarch/trunk/src/appserver/pylotengine/model/autoupdate.py", line 107, in override_with_rule retval = process() File "/home/rarch/trunk/src/appserver/pylotengine/model/autoupdate.py", line 102, in process return cfg.system_rule_allow_none(rule_name % classname, **params) File "/home/rarch/trunk/src/appserver/pylotengine/model/objects.py", line 6156, in system_rule_allow_none raise RError("System Rule '%s' caused the following exception: %r\n%s" % (rulename, e, traceback.format_exc())) RError: System Rule 'OrderDetailDiscount.process_applies' caused the following exception: AttributeError("'OrderDetail' object has no attribute 'passed_line_obj'",) Traceback (most recent call last): File "/home/rarch/trunk/src/appserver/pylotengine/model/objects.py", line 6152, in system_rule_allow_none return params['__rule_fn__']() File "OrderDetailDiscount.process_applies", line 95, in __rule_fn__ File "OrderDetailDiscount.process_applies", line 75, in exclusive_exclusions_b File "OrderDetailDiscount.process_applies", line 73, in exclusions_b File "app_startup", line 387, in kanes_discountexcluded_b File "/home/rarch/trunk/src/appserver/pylotengine/model/objects.py", line 102, in __getattr__ raise AttributeError("'%s' object has no attribute '%s'" % (self.__class__.__name__, name)) AttributeError: 'OrderDetail' object has no attribute 'passed_line_obj' 
**

**Comment by kbower** [comment]
_**kbower** trac comment on May 31, 2011, 12:42:39 PM:_

(Changeset [[1534]](../commit/e3d7f1a769e0f72769f4cc854fe59e11d961ef01))
 * add Kane's '220' discount (closes #768)
 * fix #928 (Kane's discounts cause autoupdate crash when adding package after discount)

**Comment by kbower** [comment]
_**kbower** trac status change on May 31, 2011, 12:42:39 PM:_ **closed**
